import type { Metadata } from "next";
import { Inter } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <script type="text/javascript" src="https://thedoggybrad.github.io/doom_on_js-dos/js-dos-api.js" /> */}
      

      <body className={inter.className}>{children}</body>
    </html>
  );
}
